import AppKit

@MainActor
final class SystemClipboardReader: ClipboardReader {
    /// nspasteboard.org marks for copies a clipboard history must not keep, such as passwords and one-time codes.
    private static let concealed: Set<NSPasteboard.PasteboardType> = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    private let pasteboard = NSPasteboard.general

    var changeCount: Int { pasteboard.changeCount }

    func read() -> ClipboardReading {
        ClipboardReading(
            text: pasteboard.string(forType: .string),
            isConcealed: pasteboard.pasteboardItems?.contains { !Self.concealed.isDisjoint(with: $0.types) } ?? false
        )
    }

    func write(_ text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }
}
